### PR TITLE
Add -dtfmt flag to customize output date/time format

### PR DESCRIPTION
**Pull request by mgumz**

### CODE REVIEW

**Comment by sj14** [comment]
Thanks for the contribution, boss. I'm currently thinking about leveraging https://github.com/sj14/epoch/blob/8a4b70dfec4f88681b293694ed27dc3ce35f12ac/pkg/epoch/epoch.go#L299 or something similar here.

**Comment by mgumz** [comment]
Ya, the timeformatting in itself is rather straightforward. 

I wondered more about the implications of the rest of the layout.

CleanShot 2023-04-23 at 10 11 48

So, if the left part with all the date-times is changed, the colored band is drift for sure.

**Comment by mgumz** [comment]
CleanShot 2023-04-23 at 10 24 56

**Comment by mgumz** [comment]
CleanShot 2023-04-23 at 12 03 24

**Pull request closed without merging**
